### ISSUE TITLE
install mull failed, link error.

### ISSUE THREAD

**Issue by xiaozhouqi** [mull-project/mull#1005]
1、I hava installed clang and llvm，version is 14.
      clang version 14.0.0
      Target: x86_64-unknown-linux-gnu
      Thread model: posix
      InstalledDir: /usr/local/llvm-14/bin
2、 cmake -DCMAKE_PREFIX_PATH="/usr/local/llvm-14/lib/cmake/llvm/ /usr/local/llvm-14/lib/cmake/clang/" -DCMAKE_CXX_FLAGS=-D_GLIBCXX_USE_CXX11_ABI=1 ..
3、make mull-runner-14。
Finially，I get a link error。
      /usr/bin/ld: cannot find -lLLVM
      collect2: error: ld returned 1 exit status
      tools/mull-runner/CMakeFiles/mull-runner-14.dir/build.make:210: recipe for target 'tools/mull-runner/mull-runner-14' failed
      make[3]: *** [tools/mull-runner/mull-runner-14] Error 1
      CMakeFiles/Makefile2:1992: recipe for target 'tools/mull-runner/CMakeFiles/mull-runner-14.dir/all' failed
      make[2]: *** [tools/mull-runner/CMakeFiles/mull-runner-14.dir/all] Error 2
      CMakeFiles/Makefile2:1999: recipe for target 'tools/mull-runner/CMakeFiles/mull-runner-14.dir/rule' failed
      make[1]: *** [tools/mull-runner/CMakeFiles/mull-runner-14.dir/rule] Error 2
      Makefile:719: recipe for target 'mull-runner-14' failed
      make: *** [mull-runner-14] Error 2
I don't know how to solve this problem, hope for your helpping, thank you.

**Comment by AlexDenisov** [comment]
Hi @xiaozhouqi, could you share more logs? e.g. full output from
```
cmake -DCMAKE_PREFIX_PATH="/usr/local/llvm-14/lib/cmake/llvm/ /usr/local/llvm-14/lib/cmake/clang/" -DCMAKE_CXX_FLAGS=-D_GLIBCXX_USE_CXX11_ABI=1 ..
```

Also, which OS are you running?
Note, we didn't add LLVM 14 support yet, so you can try LLVM 13 or other older version.

**Comment by AlexDenisov** [comment]
Hi @xiaozhouqi, please feel free to reopen if the issue is still not resolved.
