### ISSUE TITLE
Research is needed: Haskell support.

### ISSUE THREAD

**Issue by stanislaw** [mull-project/mull#102]

**Comment by stanislaw** [comment]
cc @michalczaplinski

**Comment by mbj** [comment]
Thats an interesting one. I'd certainly be interested to contribute. I'm working on an AST based one in private, but an compiler integrated one is a nice addition.

Lets have a chat in channel?

**Comment by stanislaw** [comment]
@mbj, #mull channel.

**Comment by mbj** [comment]
@stanislaw I'm just blocked to talk right now, I'll try to catch you there.

**Comment by stanislaw** [comment]
The first thing I would start from is to make `lli` tool to JIT a simplest hello world.

I have created a boilerplate for this here: https://github.com/mull-project/mull-jit-lab/tree/master/lab-jit-haskell.

`brew installed` ghc requires LLVM 3.7 which requires `brew install llvm@3.7`. Now there is missing `math.h` error.

@michalczaplinski, feel free to pickup from there.

**Comment by stanislaw** [comment]
@mbj no problem, we can catch up anytime. I will not work on this actively so it is either you or @michalczaplinski who expressed some interest in implementing Haskell support for Mull if that is doable.

**Comment by AlexDenisov** [comment]
Nice to have, but won't happen in the near future.
