### ISSUE TITLE
cxx_minus_to_noop produces wrong diff(patch file)

### ISSUE THREAD

**Issue by topcue** [mull-project/mull#1025]
hello.
I am reporting that mull creates an incorrect patch file.

- environment

Ubuntu 20.04
clang-12
install w/ "sudo apt-get install mull-12"

---

The `cxx_minus_to_noop` mutator works as follows.

Simple example code for bug reproducing.
- a.c.
```
#include <stdio.h>

int main() {
     int x = -1;
     int y = -x;

     return y;
}
```

- command
```
clang-12 -fexperimental-new-pass-manager \
   -fpass-plugin=/usr/lib/mull-ir-frontend-12 \
   -g -grecord-command-line \
   a.c
```

- output (killed-home_topcue_tmp_a_c-cxx_minus_to_noop-L5-C13.patch)
```
--- a/home/topcue/tmp/a.c 0
+++ b/home/topcue/tmp/a.c 0
@@ -5,1 +5,1 @@
- int y = -x;
+ int y = ;
--
Build Date: 17 Jan 2023
Commit: 3060128
LLVM Version: 12.0.0
Mull Version: 0.20.0
URL: https://github.com/mull-project/mull
```

Instead of `int y = ;`, `int y = x;` should be generated, but the patch file is generated as above.

Thanks.

**Comment by AlexDenisov** [comment]
Hi @topcue, thank you so much for bringing this up. It's very similar to the other issue (#1023) and I think I have a solution for both of these in mind. I'll do my best to address these issues soon.

**Comment by AlexDenisov** [comment]
Hi @topcue, the issue is fixed [here](https://github.com/mull-project/mull/pull/1026). I'll cut the new release soon.

**Comment by AlexDenisov** [comment]
Here we go https://github.com/mull-project/mull/releases/tag/0.21.0

**Comment by topcue** [comment]
Thanks!
