### ISSUE TITLE
Lenovo website won't load

### ISSUE THREAD

**Issue by robsmith11** [mull-project/mull#1031]
It works fine with Firefox from the play store and Fennec from fdroid.

For example, try to open this and the pictures of the different models won't load:

https://www.lenovo.com/us/en/laptops/subseries-results?visibleDatas=698%3AThinkPad&IPromoID=LEN969625

**Comment by AlexDenisov** [comment]
Hi @robsmith11, I believe this is a wrong place for the report - this is not a browser project 😃
