### ISSUE TITLE
Timeout for SQLite

### ISSUE THREAD

**Issue by bajinsheng** [mull-project/mull#1033]
I have some troubles when running mull with SQLite:
```shell
git clone https://github.com/sqlite/sqlite
cd sqlite
./configure --enable-all CC=clang CFLAGS="-fexperimental-new-pass-manager -fpass-plugin=/usr/lib/mull-ir-frontend-14 -g -grecord-command-line"
make
echo "SELECT 1;" > test.sql
mull-runner-14 ./sqlite3 < test.sql
````

I got these info:
```shell
[info] Warm up run (threads: 1)
       [################################] 1/1. Finished in 20021ms
[warning] Original test failed
status: Timedout
stdout: ''
stderr: ''
```

Even if I enlarge the time to 10 seconds in the configuration file, I still got this error.

**Comment by bajinsheng** [comment]
Thanks for your reply!

Yes, it works and does not time out.
However, it prompts "[info] No mutants found. Mutation score: infinitely high"
I don't set up the mull.yml file, but I guess it should have a default configure and should not have no mutations?

**Comment by AlexDenisov** [comment]
Yes, I'd expect at least some mutants to be there with a default config.
Do you see any warnings/errors produced by Mull when you build sqlite?

**Comment by bajinsheng** [comment]
```shell
error: unable to handle compilation, expected exactly one compiler job in ' "/usr/lib/llvm-15/bin/clang" "-cc1" ... "sqlite3.c"; '
[warning] Cannot parse file: '/home/sqlite_mutation/sqlite3.c':
/usr/lib/llvm-15/bin/clang -fno-legacy-pass-manager -fpass-plugin=/usr/lib/mull-ir-frontend-15 -g -grecord-command-line -I ... -o sqlite3 shell.c sqlite3.c
Make sure that the flags provided to Mull are the same flags that are used for normal compilation.
```
Yes. There is an error that shows mull can not parse the file.

**Comment by bajinsheng** [comment]
Solved by removing the parameter `-grecord-command-line`
