### ISSUE TITLE
How to check customized logic

### ISSUE THREAD

**Issue by bajinsheng** [mull-project/mull#1034]
I want to check whether the program returns the correct results, instead of exit 0 or 1. How do I do that?

**Comment by m42e** [comment]
This should be done in your tests. And the tests then should return the final error code.
If a mutation is active and the mutant returns exit code 0 when executed, mull detects a surviving mutant.

**Comment by AlexDenisov** [comment]
@bajinsheng either as Matthias suggested above, or you can use the sqlite reporter and then inspect the content of the database. There you will have `stderr`/`stdout` for each invocation and you can do any kinds of inspections either manually, or with some hand-crafted scripts.

**Comment by bajinsheng** [comment]
I see. Thanks for your reply!
