### ISSUE TITLE
Testing dynamic libraries

### ISSUE THREAD

**Issue by pseusys** [mull-project/mull#1041]
Good afternoon!
I'm really interesting in using `mull` in the following setup: I have a simple executable (that doesn't require being tested) and a several dynamic libraries (`*.so` files) that I would like to test. My first obvious try was using [non-standard test suite tutorial](https://mull.readthedocs.io/en/0.21.0/tutorials/NonStandardTestSuite.html), specifying the library file path (one by one) for the `mull-runner` instead of the executable, like this: `mull-runner /path/to/first/dynamic/library.so --ide-reporter-show-killed --test-program=/path/to/executable`, but it didn't work.
Could you give me any advice, is there a way to perform mutation testing of my dynamic libraries?..

**Comment by AlexDenisov** [comment]
@pseusys could you share more details on what exactly didn't work?

**Comment by AlexDenisov** [comment]
Please, feel free to reopen whenever you have more details.
