### ISSUE TITLE
Allow a configurable percentage of mutants to live without returning error

### ISSUE THREAD

**Issue by mpownby** [mull-project/mull#1053]
Hi, I created a PR to add this feature ( https://github.com/mull-project/mull/pull/1052 ) and wasn't sure if anyone saw it since I apparently can't assign it to anyone.  So this issue is just to raise visibility.

Thanks for your consideration.

**Comment by AlexDenisov** [comment]
#1052 merged and the new version is now released https://github.com/mull-project/mull/releases/tag/0.23.0

@mpownby thank you for working on this, highly appreciated!
