### ISSUE TITLE
Mutation Operators

### ISSUE THREAD

**Issue by AlexDenisov** [mull-project/mull#107]
We need to choose and implement more mutation operators.

**Comment by mbj** [comment]
Do you have a classification yet for operators?

**Comment by mbj** [comment]
@AlexDenisov There are various classes I could observe so far, but I missed to do a consistent write up on them. I'd like to do a small brian storming session via hangout if you wanted. As I always wanted to start writing down my thoughts on classification from my (mutants) perspective I'd need the opportunity to bounce ideas of another mind.

Are you availabe for such a thing this week?

**Comment by AlexDenisov** [comment]
@mbj, sorry, I was busy. We can talk when you have few minutes.

**Comment by mbj** [comment]
@AlexDenisov I'm available later the day, late EU night.

**Comment by stanislaw** [comment]
Closing this as too broad. We have a few operators now 😄
