### ISSUE TITLE
Mutated modules live in memory

### ISSUE THREAD

**Issue by AlexDenisov** [mull-project/mull#135]
All the mutated modules live in memory even though they are not needed.
We need to find a way to remove them as soon as they are not needed.

**Comment by stanislaw** [comment]
+1 for having this sooner!

**Comment by stanislaw** [comment]
+1 for having this sooner!

**Comment by AlexDenisov** [comment]
This is what I've got recently on CentOS with 2GB of RAM in VirtualBox:
```
Failed to create watchdog after creating 1012 child processes
Cannot allocate memory
Shutting down
```
😞
