### ISSUE TITLE
Add default mutation operators to Config constructor

### ISSUE THREAD

**Issue by Quolyk** [mull-project/mull#159]
This task includes following. Suppose we init config from yaml with mutaton operators: `add`, `negate`. If Config constructor has default mutation operators : `negate`, `add`, `remove`, than `YAMLTraits` will map: `add` -> `negate`, `negate` -> `add`, thus producing following: `add`, `negate`, `remove` instead of `add`, `negate`.

**Comment by stanislaw** [comment]
@Quolyk I now see that you mean something different, not just parsing default 3 values from a YAML file correctly. I would recommend you to add a unit test to demonstrate a specific behavior you're talking about here.
