### ISSUE TITLE
config.yml: Blacklist mutation points from specific locations.

### ISSUE THREAD

**Issue by stanislaw** [mull-project/mull#165]
The most known sources of a noise for Mull's mutation reports:

`include/c++/v1`
`include/llvm`

Would be great to filter these out by just specifying them in config.yml like:

```
exclude_locations:
- include/c++/v1
- include/llvm
```

Another candidate: `blacklist_locations:`.

**Comment by stanislaw** [comment]
@AlexDenisov what is better: exclude_locations or blacklist_locations or ... ?

**Comment by AlexDenisov** [comment]
`exclude_locations` is better, IMO.
I think `include/c++/v1` filter should be hard coded.

**Comment by stanislaw** [comment]
Closed by #166 .
