### ISSUE TITLE
Add Catch support

### ISSUE THREAD

**Issue by AlexDenisov** [mull-project/mull#175]
https://github.com/philsquared/Catch

**Comment by torfinnberset** [comment]
It should be Catch2 at this point, but yes this is a highly desired feature for those who have just ported all their tests from GoogleTest :) 

Is there an overview of what would be needed for this to be implemented? What's a recommended place to start looking at it?

**Comment by AlexDenisov** [comment]
@torfinnberset you are right, the issue is quite dated 😄 

First of all, it is worth mentioning that one can use Mull with Catch2 by simply using `--test-framework=CustomTest`, the result won't be a bit less accurate, but it works and a great place to start.

Essentially, to add a new framework support one needs to implement one class: `*TestFinder`, which is `Catch2TestFinder` in this case. Here is an example: [GoogleTestFinder](https://github.com/mull-project/mull/blob/master/lib/TestFrameworks/GoogleTest/GoogleTestFinder.cpp).
It has only one function that returns an array of tests that are found in the program.

The test has the following properties:

 - testName: just a name of the test
 - programName: the `argv[0]` that will be passed by Mull to the program being tested, it can be any arbitrary string unless some special value is needed by the test framework. We use `mull` as a default value.
 - driverFunctionName: the main function of the program that is being tested, normally it is `main` unless a test framework is a tricky one
 - args: array of strings that will be passed to the `driverFunctionName`, basically it corresponds to the `argv`. It is expected that the test framework in question can run single test based on some arguments passed, e.g.: `--gtest_filter=FooTest.barTest` for GoogleTest.
 - testBody: a pointer to an LLVM function that represents actual test function.

So the very step is to find a way to find the `testBody` function in the LLVM IR programmatically, for that you can simply compile a Catch2 test into the bitcode and look at it manually (`clang -s -emit-llvm test.cpp`). Then, it makes sense to add a new test to the `mull-test` target, the test can point to the hardcoded path to the corresponding LLVM Bitcode file, and the last step is to integrate the example test into the `tests/fixtures` somehow.

(The paragraph above is not necessarily the best approach, but that is how I would do it :) )

---

@torfinnberset I hope it helps, feel to drop any other questions here or on Slack.

**Comment by torfinnberset** [comment]
@AlexDenisov thanks for the detailed explanation! I have no experience with LLVM, other than just using Clang as a compiler. That being said, I'd still like to give it a try. 

However, I'm reading that Catch2 has now released it's final v2 version, and will undergo many breaking changes for the next major release. I think I will wait on that version to be released to start implementing anything, as I don't want to be out of date the day after I (hopefully) finish :)

**Comment by AlexDenisov** [comment]
Sure, I think this issue still will be opened by that time 😄
