### ISSUE TITLE
Failing test on Ubuntu

### ISSUE THREAD

**Issue by Mrtj2016** [mull-project/mull#349]
I just followed the steps of GettingStartedUbuntu.md, and it failed at running tests. Here is the report.

> root@tang-virtual-machine:/opt/mull# make test
mkdir /opt/mull/BuildNinja
rm -rfv /opt/mull/BuildNinja/CMakeCache.txt
cd /opt/mull/BuildNinja && cmake -G Ninja \
    -DCMAKE_INSTALL_PREFIX=/usr/local \\
     \\
    -DLLVM_ROOT=/usr/lib/llvm-3.9 \\
    -DMULL_SUPPORT_RUST=0 \\
    ../
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler using: Ninja
-- Check for working C compiler using: Ninja -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler using: Ninja
-- Check for working CXX compiler using: Ninja -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- googletest> Creating google-test target...
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
MULL_DEPENDENCY_LIBCLANG
    linked by target "mull" in directory /opt/mull/lib
MULL_DEPENDENCY_LIBCLANG_ANALYSIS
    linked by target "mull" in directory /opt/mull/lib
MULL_DEPENDENCY_LIBCLANG_AST
    linked by target "mull" in directory /opt/mull/lib
MULL_DEPENDENCY_LIBCLANG_BASIC
    linked by target "mull" in directory /opt/mull/lib
MULL_DEPENDENCY_LIBCLANG_DRIVER
    linked by target "mull" in directory /opt/mull/lib
MULL_DEPENDENCY_LIBCLANG_EDIT
    linked by target "mull" in directory /opt/mull/lib
MULL_DEPENDENCY_LIBCLANG_FRONTEND
    linked by target "mull" in directory /opt/mull/lib
MULL_DEPENDENCY_LIBCLANG_LEX
    linked by target "mull" in directory /opt/mull/lib
MULL_DEPENDENCY_LIBCLANG_PARSE
    linked by target "mull" in directory /opt/mull/lib
MULL_DEPENDENCY_LIBCLANG_SEMA
    linked by target "mull" in directory /opt/mull/lib
MULL_DEPENDENCY_LIBCLANG_SERIALIZATION
    linked by target "mull" in directory /opt/mull/lib
MULL_DEPENDENCY_LIBCLANG_TOOLING
    linked by target "mull" in directory /opt/mull/lib
--Configuring incomplete, errors occurred!
See also "/opt/mull/BuildNinja/CMakeFiles/CMakeOutput.log".
See also "/opt/mull/BuildNinja/CMakeFiles/CMakeError.log".
Makefile:52: recipe for target 'ninja.init' failed
make: *** [ninja.init] Error 1

**Comment by AlexDenisov** [comment]
Hi @Mrtj2016, thank you for the feedback.
Seems like the doc is missing another required package: `libclang-3.9-dev`.
Could you please install it and try again?
```
sudo apt-get install -y libclang-3.9-dev
make clean
make test
```

**Comment by Mrtj2016** [comment]
Hi @AlexDenisov , thanks for your help, and it works well now.

**Comment by AlexDenisov** [comment]
Great, I am happy to hear that.
Please, do not hesitate to open more issues if you have any problems with Mull.
We appreciate your feedback, @Mrtj2016!
