### ISSUE TITLE
Make Mutation Operators configurable

### ISSUE THREAD

**Issue by AlexDenisov** [mull-project/mull#39]
At the moment we have only two operators, but they configurable only via recompilation.
It would be extremely helpful if we can configure them simply by changing the config.

**Comment by Quolyk** [comment]
I want to make this one. @AlexDenisov Could you express this task in detail?

**Comment by AlexDenisov** [comment]
@Quolyk if you look at the constructor of `GoogleTestFinder`, then you will find that three mutation operators simply hard coded.
The goal is to extend the configuration so that one can specify all required operators. Basically, you will need to add another property to config, instantiate all mutation operators and inject them into a test finder.
