### ISSUE TITLE
Setup CI for FreeBSD

### ISSUE THREAD

**Issue by AlexDenisov** [mull-project/mull#414]
There is another nice service we might consider: https://cirrus-ci.org

**Comment by AlexDenisov** [comment]
Vagrant + Ansible setup is also needed for this.

**Comment by XVilka** [comment]
You can use [SourceHut](https://sourcehut.org), it supports FreeBSD and OpenBSD now, NetBSD is work in progress: https://man.sr.ht/builds.sr.ht/compatibility.md#freebsd

**Comment by AlexDenisov** [comment]
Wow, this is awesome! Thanks for the hint @XVilka, I'll definitely give it a try.

**Comment by AlexDenisov** [comment]
Closed as per #562.
