### ISSUE TITLE
Research: Easy process of a compilation to LLVM IR.

### ISSUE THREAD

**Issue by stanislaw** [mull-project/mull#49]
I have requested CMake to give us some information: [[cmake-developers] Question / Feature request: LLVM bitcode target](https://cmake.org/pipermail/cmake-developers/2017-January/029788.html).

Relevant discussion: [[cmake-developers] Requesting Advice: Installing object files](https://cmake.org/pipermail/cmake-developers/2017-January/029792.html) where it is being asked about very similar thing.

**Comment by stanislaw** [comment]
I have updated description here. cc @AlexDenisov @Quolyk @JDevlieghere

**Comment by stanislaw** [comment]
As of May 2017, we have two working approaches:

1) **current approach with a custom `mull-clang wrapper**

This wrapper adds `-emit-llvm` in compiler mode and writes all the files from a link list to a specific directory like `tmp/mull_bitcode_files` in a linker mode.

This approach is used in [mull-auto-test](https://github.com/mull-project/mull-auto-test)

2) **newer, experimental: LTO**

```
cmake -G Ninja -DLLVM_ENABLE_LTO=full ../llvm/
ninja ADTTests
```

This is a newer approach we found, it is possible that it will make things easier and eventually replace approach #1.

**Comment by AlexDenisov** [comment]
@stanislaw shall we consider it as done (at least for C++)? I do not see what else can we do in this case.
