### ISSUE TITLE
RHEL 6 binary

### ISSUE THREAD

**Issue by xor2003** [mull-project/mull#518]
Could you please prepare binary for RHEL 6 or static or something like flat pack?

**Comment by AlexDenisov** [comment]
TL;DR: I will definitely take a look into it, but it may take time.

---
For releases we rely on precompiled binaries from http://releases.llvm.org.
There is no (recent) binary for RHEL, which means we need to compile LLVM ourselves, which is not currently supported by our release scripts.

**Comment by AlexDenisov** [comment]
Seems like this is not going to happen in the nearest future since everyone is busy :)
I'm closing this one, but contributions are very welcome.
