### ISSUE TITLE
Assertion `sourceLocation.column < line.size()' failed.

### ISSUE THREAD

**Issue by WisniewskiP** [mull-project/mull#519]
I'm trying to use mull, after some start problem I got it running.

Unfortunately after printing some output I get:
mull-cxx: /opt/mull/lib/Reporters/IDEReporter.cpp:84: void printSurvivedMutant(SourceManager &, const mull::MutationPoint &): Assertion `sourceLocation.column < line.size()' failed.

If you need more information let me know.

Version: 0.2

**Comment by AlexDenisov** [comment]
Good news: this is the last step of the execution, which means that everything else works great :)

Now let's try to debug it.

1. Do you enable any specific mutators or do you stick to the default ones?

2. Did you compile the project with debug information enabled (`-g`) ?

3. Do you have any other output? The very last print before the assert should be something like:

`/foo/bar/buzz.c:18:15: warning: <mutation description>`

The key point here is the line (`18`) and the column (`15`). Could you confirm that the `line` in your case has at least `column` characters in it?

**Comment by WisniewskiP** [comment]
1. I used default ones
2.  I compiled my code with `-Og -g3`
3. last line looks like this:
`/build/build/../RTOS/src/OS/Sync/Impl/EventQueueImpl.cpp:0:0: warning: Negate Condition: replaced == with !=`

**Comment by AlexDenisov** [comment]
All right, it means that there is no debug information for the mutated instruction.
I will take another look into what could led to this issue.

Meanwhile, would you be willing to give a try to the [junk detection](https://github.com/mull-project/mull#junk-mutations) feature? It is still experimental and not robust, but it may help to get better results. To use it you need to provide `mull-cxx` with the compilation flags and/or compilation database. Something like this:

```
mull-cxx -compilation-flags="-I /usr/include -I /usr/local/include" -compdb-path=/build/build/compile_commands.json path-to-the-binary
```

**Comment by AlexDenisov** [comment]
Actually, here is a better example if you do not have the compilation database:
https://github.com/mull-project/mull#examples-openssl

**Comment by WisniewskiP** [comment]
I tried junk detection with compilation database: 
`Filtering out junk mutations (threads: 3): 30/83Segmentation fault`

I think I will make separate ticket for this issue with backtrace.

**Comment by AlexDenisov** [comment]
Closing this one as well. Please, see #520 and #524 for more details.

And again, feel free to re-open.
