### ISSUE TITLE
git command for "Hacking on Mull" missing "--recursive" flag

### ISSUE THREAD

**Issue by colimitt** [mull-project/mull#527]
The the git command for the installation instruction about installing mull "Hacking on Mull", seems to be missing "--recursive":

git clone https://github.com/mull-project/mull.git

seems should be 
git clone https://github.com/mull-project/mull.git --recursive

**Comment by AlexDenisov** [comment]
Hi @colimitt, you are right. Would you like to send a pull request with the correction?
