### ISSUE TITLE
SQLiteReporter: escape symbols properly.

### ISSUE THREAD

**Issue by stanislaw** [mull-project/mull#53]
```
Results can be found at '/Users/stanislaw/Projects/LLVM/BuildXcode/Debug/bin/1479765000.sqlite'
Cannot execute 'INSERT INTO execution_result VALUES ('0','0','','LLVM ERROR: Program used external function '__ZTIN4llvm20SectionMemoryManagerE' which could not be resolved!
');'
```

**Comment by Quolyk** [comment]
How can I reproduce this? SQLiteReporter test seems normal.

**Comment by stanislaw** [comment]
@Quolyk can be that it has gone. At least I have completely lost original context. Will close :)

**Comment by AlexDenisov** [comment]
@Quolyk @stanislaw it's not gone.
There are two places where we insert `execution_result` into a database: around lines 79 and 155.
We do it properly only In the second case.

**Comment by stanislaw** [comment]
@Quolyk are you willing to make a contribution? We are happy to help if you are :)

You could extend https://github.com/mull-project/mull/blob/master/unittests/SQLiteReporterTest.cpp with a test that would write the failing line from:

```
Cannot execute 'INSERT INTO execution_result VALUES ('0','0','','LLVM ERROR: Program used external function '__ZTIN4llvm20SectionMemoryManagerE' which could not be resolved!
```

P.S. This is how I would do it :)

**Comment by Quolyk** [comment]
@stanislaw I want to make a contribution :) Thanks for the help.

**Comment by Quolyk** [comment]
How can I create such test?
I suppose I should make `ExecutionResult` that produces 
`'LLVM ERROR: Program used external function '__ZTIN4llvm20SectionMemoryManagerE' which could not be resolved!`?
Btw, there are no `MutationResults` in `TestResult`

**Comment by AlexDenisov** [comment]
You can try to construct an execution result with `stderrOutput` equal to `'LLVM ERROR: Program used external function '__ZTIN4llvm20SectionMemoryManagerE' which could not be resolved!` and attempt to save it.

**Comment by stanislaw** [comment]
Thanks @Quolyk !
