### ISSUE TITLE
LLVM ERROR: 64-bit code requested on a subtarget that doesn't support it!

### ISSUE THREAD

**Issue by apmanol** [mull-project/mull#538]
Hello,

trying to compile a test project in a 64bit environment with the  addition of `-m32` flag, which compiles and runs and it should. 

``` bash
cmake -E make_directory build_mut
cmake -H. -Bbuild_mut -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr -Dwith_test=ON  -DCMAKE_C_FLAGS="-m32 -fembed-bitcode" -DCMAKE_CXX_FLAGS="-m32 -fembed-bitcode" -DOPENSSL_CRYPTO_LIBRARY:FILEPATH=/usr/lib/libcrypto.so -DOPENSSL_INCLUDE_DIR:PATH=/usr/include -DOPENSSL_SSL_LIBRARY:FILEPATH=/usr/lib/libssl.so -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON -DCMAKE_C_COMPILER=/opt/clang70/bin/clang -DCMAKE_CXX_COMPILER=/opt/clang70/bin/clang++ -DCMAKE_POSITION_INDEPENDENT_CODE=ON
```
But when trying to run the `mull-cxx`:

```bash
mull-cxx -test-framework=GoogleTest -compdb-path=./ -ld_search_path=/usr/lib  -mutators=math_add_mutator ./testBin/my_check

Extracting bitcode from executable (threads: 1): 1/1. Finished in 21ms.
Loading bitcode files (threads: 7): 7/7. Finished in 162ms.
Compiling instrumented code (threads: 7): 0/7LLVM ERROR: 64-bit code requested on a subtarget that doesn't support it!

```
The compilation flags contains the `-m32` flag. 

Any tip on how to overcome this issue?

**Comment by AlexDenisov** [comment]
Hi @apmanol, you need to also compile Mull for x32 then.

Mull uses JIT to run the tests and the JIT engine cannot run x32 programs when it's compiled in x64 mode.

I'm actually doing exactly this right now, I will add instructions on how to do this during the next 30 minutes or so.

**Comment by apmanol** [comment]
@AlexDenisov Thanks a lot for the prompt answer!

**Comment by AlexDenisov** [comment]
Here is the instruction:

```
git clone https://github.com/mull-project/mull.git -b x32 --recursive
git clone https://github.com/llvm/llvm-project.git -b release/8.x
mkdir build.dir
cd build.dir
cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DMULL_BUILD_32_BITS=On -DPATH_TO_LLVM=../llvm-project/llvm ../mull
ninja mull-cxx
```

That should work, let me know if you get any other issues.

**Comment by apmanol** [comment]
> Here is the instruction:
> 
> ```
> git clone https://github.com/mull-project/mull.git -b x32 --recursive
> git clone https://github.com/llvm/llvm-project.git -b release/8.x
> mkdir build.dir
> cd build.dir
> cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DMULL_BUILD_32_BITS=On -DPATH_TO_LLVM=../llvm-project/llvm ../mull
> ninja mull-cxx
> ```

It can't find the correct type(32bit) of `libsqlite3` if there are both (64bit && 32bit) in the system.

**Comment by AlexDenisov** [comment]
@apmanol which distro are you on? I'm using macOS and haven't seen this issue before.

**Comment by apmanol** [comment]
FC 29, but this is the general case because it is based on `pkg_check_modules` and for some reason prefers the 64bit version.

**Comment by AlexDenisov** [comment]
Unfortunately, I could not find a solution to this issue. The best I can do is to try providing prebuilt packages for i386. Would that help @apmanol?

**Comment by apmanol** [comment]
No worries, it's a classic issue with those `cmake` magics, I will modify the `cmakelist.txt` to find the appropriate lib.

**Comment by AlexDenisov** [comment]
No plans to support 32bits unless anyone volunteers to take care of it.

**Comment by apmanol** [comment]
No worries, thanks for the nice software you support!
