### ISSUE TITLE
mutation-testing-elements does not work with local .json file

### ISSUE THREAD

**Issue by pr0g** [mull-project/mull#567]
Hey there,

I just started experimenting with the mull project and it seems really cool! (I discovered it while listening to CppCast 🙂)

I have managed to get everything to run but ran into an issue when trying to open the generated .html file when `-reporters=Elements` is specified. When trying to open the page I'd get an error that the local .json file could not be loaded.

As a quick test I used http://myjson.com/ to create a url for the json source and when using that with the `<mutation-test-report-app src=""` element, it worked.

If this issue is more for the https://github.com/stryker-mutator/mutation-testing-elements repo please let me know and I'll close this issue and ask about it there.

Thanks for your time,

Cheers,

Tom

**Comment by AlexDenisov** [comment]
Hi @pr0g, thanks for the heads up on the issue: I planned to elaborate on the usage of mutation elements, but still didn't get to it.

The best way to go is to start an HTTP-server locally and open the HTML page through it.
E.g.:
```
python -m SimpleHTTPServer 8000
```
then go to [http://localhost:8000](http://localhost:8000) and open desired HTML-report.

Let me know if it does not work 😉

P.S. The elements reporter is an experimental feature we are still testing. We would appreciate if you report any other issues you will see.

**Comment by pr0g** [comment]
Hi @AlexDenisov,

Thank you very much for the quick response! 🙂

Ah no worries at all, yes I see this was added very recently, looks like a great addition! 😄

Ah great idea, I should have thought of that 🙈Just tested it locally and that works perfectly!

Sure thing will do!

P.S. Please feel free to close this issue if you wish as there's a quick and easy workaround - hopefully anyone else running into this issue will find this answer here.
