### ISSUE TITLE
Rename everything from "mutang" to "mull"

### ISSUE THREAD

**Issue by AlexDenisov** [mull-project/mull#57]

**Comment by JDevlieghere** [comment]
While doing so we should also make the current `Mutang` namespace start with a lowercase letter.

**Comment by stanislaw** [comment]
Why lowercase?

**Comment by JDevlieghere** [comment]
For consistency. It's common practice to use lowercase with underscores for namespaces. The standard does this and so do almost all C++ projects, including LLVM for example.
