### ISSUE TITLE
Is Rust still supported?

### ISSUE THREAD

**Issue by bbigras** [mull-project/mull#580]
I found this project with Google but 242b3ec68bb27b5c59479905719db79e2f18b35f seems to have removed Rust support.

Is Rust still supported?

**Comment by AlexDenisov** [comment]
We had a very basic proof of concent that worked, but we stopped developing it for two reasons:
1. Not enough human-power to focus on this part.
2. @llogiq started working on 'native' tool for Rust: https://github.com/llogiq/mutagen

That being said, we may get to Rust implementation eventually, but it's not on the todo-list in any foreseeable future.

I will close the issue, please do not hesitate to reopen it if you have any further questions.

**Comment by llogiq** [comment]
Just for the record, I think there is place for multiple tools. mutagen is as of yet very limited, and though a rewrite effort is underway, there are some mutations it will never be able to introduce.

**Comment by bbigras** [comment]
Gotcha, thanks @AlexDenisov 

> and though a rewrite effort is underway, there are some mutations it will never be able to introduce.

@llogiq do you mean that mull with Rust support would still be great since it would allow those mutations or that mull would have the same limitation?

**Comment by llogiq** [comment]
mutagen is fairly limited because its mutations must not fail, whereas mull can recover from failed mutation attempts.
