### ISSUE TITLE
status: crashed on test: main, no mutants found

### ISSUE THREAD

**Issue by assaaassin** [mull-project/mull#586]
I'm using pre-built binary for mull (Ubuntu 18.04) with LLVM 8.0 and Clang 8.0. At first, I had problem building openssl but then I modified its Makefile to compile with clang instead of gcc and it built successfully. However, now I am trying to run mull-cxx on test/bio_enc_test and it's giving me the following output:
```
$ mull-cxx -test-framework=CustomTest \
 -compilation-flags="-I . -I crypto/modes -I crypto/include -I include -I apps \
 -isystem /usr/local/include \ 
 -isystem /usr/include \ 
 -isystem /usr/include/clang/8.0.1/include \
 -isystem /usr/include/x86_64-linux-gnu" \ 
  test/bio_enc_test -ld_search_path /lib/x86_64-linux-gnu
Extracting bitcode from executable (threads: 1): 1/1. Finished in 159ms.
Loading bitcode files (threads: 8): 634/634. Finished in 254ms.
Compiling instrumented code (threads: 8): 634/634. Finished in 12ms.
Loading dynamic libraries (threads: 1): 1/1. Finished in 0ms.
Searching tests (threads: 1): 1/1. Finished in 4ms.
Preparing original test run (threads: 1): 1/1. Finished in 171ms.
Running original tests (threads: 1): 0/1
test: main
status: Crashed
stdout: ''
stderr: ''
Running original tests (threads: 1): 1/1. Finished in 122ms.
No mutants found. Mutation score: infinitely high

Total execution time: 734ms
`
```

Any idea what's causing this crash? I have examined the binary with readelf and confirmed that it has the .llvmbc section which means -fembed-bitcode is working just fine. Any help would be much appreciated.

**Comment by AlexDenisov** [comment]
Could you try running without sandbox?
‘-sandbox=None’
Maybe we’ll see some hints.
Otherwise, could you share how you build OpenSSL including the commit sha?

**Comment by assaaassin** [comment]
Adding '-sandbox=None' to the arguments gives a segmentation fault. 
```

$ mull-cxx -test-framework=CustomTest -compilation-flags="-I . -I crypto/modes -I crypto/include -I include -I apps -isystem /usr/local/include -isystem /usr/include -isystem /usr/include/clang/8.0.1/include -isystem /usr/include/x86_64-linux-gnu" test/bio_enc_test -ld_search_path /lib/x86_64-linux-gnu -sandbox=None
Extracting bitcode from executable (threads: 1): 1/1. Finished in 167ms.
Loading bitcode files (threads: 8): 634/634. Finished in 212ms.
Compiling instrumented code (threads: 8): 634/634. Finished in 11ms.
Loading dynamic libraries (threads: 1): 1/1. Finished in 0ms.
Searching tests (threads: 1): 1/1. Finished in 2ms.
Preparing original test run (threads: 1): 1/1. Finished in 100ms.
Running original tests (threads: 1): 0/1Segmentation fault (core dumped)

```
I build openSSL pretty much the same way as mentioned the README. I clone the repo (sha: be66a15cc1a4c3cc68fa854ceea321ca57f96304) and config using
```
$ ./config -no-asm -no-shared -g -O0 -fembed-bitcode
```

Once the Makefile is generated, I modify the CC and CXX flags to clang and clang++ respectively. I have to do this otherwise 'make all' fails with an error that -fembed-bitcode is an invalid parameter. After this, I simply do:
```
$ make depend
$ make all
```
Then it builds successfully.

**Comment by assaaassin** [comment]
@AlexDenisov I would really appreciate a solution to my problem :)

**Comment by AlexDenisov** [comment]
Thanks for reminder @assaaassin, I can reproduce the issue. I'll take a look and then get back to you.

**Comment by AlexDenisov** [comment]
@assaaassin I didn't get to the exact solution for this problem, but the root of the problem should be covered by #628.
Originally, LLVM complained about missing/unresolved symbols when loading the program into JIT engine. We relied on this behavior. At some point this feature was removed from the component we used and in the end one was always getting an unresolved function address (basically NULL), which led to a crash whenever you run such a program.
I assume, this is the case with this issue, and probably also with #528 and #534.

I will have another debugging session later this week. Meanwhile, I can only suggest you to build Mull from the master branch and give it a try yourself.

**Comment by AlexDenisov** [comment]
It took a bit longer than I expected, but the issue indeed was uncovered by the #628.

On Linux, JIT could not resolve `pthread_atfork` symbol. The easiest solution is to build OpenSSL without thread support (`-no-threads`), i.e.:

```
./config -no-asm -no-shared -no-threads -g -O0 -fembed-bitcode
```

With this configuration, everything works as expected.
I'll update documentation/tutorial shortly

**Comment by AlexDenisov** [comment]
@assaaassin the updated tutorial is here[1], in case you are still interested :)

[1] https://mull.readthedocs.io/en/latest/OpenSSLTutorial.html
