### ISSUE TITLE
is it possible to save the source code level mutant record? I want to analysis them #10198

### ISSUE THREAD

**Issue by Marvinmw** [mull-project/mull#587]
is is possible to save the source code level mutant record? I want to analysis them #10198

**Comment by AlexDenisov** [comment]
Unfortunately not at the moment. There is something in the works and on our todo list, though.

I'll notify you when we have this in place.

**Comment by ligurio** [comment]
Mutations in source code are part of Mull report (type Elements). It is not so difficult to create real patches from these changes.
(btw I do it using https://github.com/ligurio/py-mutation-testing-elements)

**Comment by AlexDenisov** [comment]
It took some time to get there, thanks @m42e for the effort!
@Marvinmw this is resolved now (via #911).
