### ISSUE TITLE
Debug module to provide debugging functions for everything in the Mull's source code

### ISSUE THREAD

**Issue by stanislaw** [mull-project/mull#596]
We spend quite some time debugging everything. It would be great if there would be a `dump()` method with the overloads for every class from clang::*, llvm::* and mull::*.

One way of doing it is to simply create `Debugging` folder in the Mull's source code and put all of the overloads there.

The first MR can be adding just a few of the most touched classes.

**Comment by AlexDenisov** [comment]
Let's have a more specific, actionable list. @stanislaw I encourage you to create a separate issue, or better a number of issues for each class you want to be `dump`able.
