### ISSUE TITLE
Possible bug: mutation points are duplicated in the Elements report

### ISSUE THREAD

**Issue by stanislaw** [mull-project/mull#601]
This report looks similar to what I have opened before: https://github.com/mull-project/mull/issues/522 but this time it is known that it is no longer a code from template functions or mutations inlined from the headers, but a normal .cpp code.

I am comparing the mutation results for the exercise of proving that https://github.com/mull-project/mull/pull/582 works. The difficulty is related to the fact that both reports see duplicated mutation points so it is not clear which kind of improvement the #582 actually brings.

My guess that the problem can hide in one of the following areas:

1) Finding the mutations in the IR. There is some chance that more than one mutator responds to a given instruction location.

2) Some wrong things done by the Elements Reporter (unlikely).

**Comment by AlexDenisov** [comment]
There is not enough input to act on this issue. Feel free to reopen if there is more input.
