### ISSUE TITLE
YAML "unexpected scalar" Error when loading compilation database generated from Clang -MJ

### ISSUE THREAD

**Issue by Warwolt** [mull-project/mull#629]
I'm running Mull 0.5.0 for Ubuntu 18.04 running on WSL1, and launched it with the -compdb-path option pointing to a compilation database json file generated by Clang. 

I'm compiling each c source-file using Clang 6.0.0-1ubuntu2, with the -MJ command for generating a json-file per object file (*.o.json). I then use Sed to stitch together all the individual json-files into a compilation database based on this [link](https://github.com/cquery-project/cquery/wiki/Compilation-database).

My current compilation-database looks like this (only one source-file currently under test):
```JSON
[
    {
        "directory": "/root/code/c/unit-test-experiments/mull_mutation_testing/build",
        "file": "../sw/src/millisec_timer_unix.c",
        "output": "/tmp/millisec_timer_unix-19be99.bc",
        "arguments": [
            "/usr/lib/llvm-6.0/bin/clang",
            "-xc",
            "../sw/src/millisec_timer_unix.c",
            "-c",
            "-Wall",
            "-Werror",
            "-fembed-bitcode=all",
            "-g",
            "-I",
            "../sw/inc",
            "-I",
            "../sw/test/fakes",
            "-I",
            "../lib/fakefunctionframework",
            "-o",
            "obj/millisec_timer_unix.o",
            "--target=x86_64-pc-linux-gnu"
        ]
    }
]
```

The command used to run Mull was:
```
mull-cxx -test-framework=GoogleTest -mutators=default -ld_search_path=/lib/x86_64-linux-gnu/ -ld_search_path=/usr/lib/x86_64-linux-gnu/ -ld_search_path=/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/ -exclude-path=lib -exclude-path=sw/test -exclude-path=googletest -compdb-path=./compile_commands.json ./test
```

The error given is:
```
mull-cxx -test-framework=GoogleTest -mutators=default -ld_search_path=/lib/x86_64-linux-gnu/ -ld_search_path=/usr/lib/x86_64-linux-gnu/ -ld_search_path=/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/ -exclude-path=lib -exclude-path=sw/test -exclude-path=googletest -compdb-path=./compile_commands.json ./test
Extracting bitcode from executable (threads: 1): 1/1. Finished in 23ms.
Loading bitcode files (threads: 4): 5/5. Finished in 209ms.
YAML:7:13: error: unexpected scalar
            "/usr/lib/llvm-6.0/bin/clang",
            ^
Can not read compilation database: ./compile_commands.json
Compiling instrumented code (threads: 4): 5/5. Finished in 12ms.
Loading dynamic libraries (threads: 1): 1/1. Finished in 1ms.
Searching tests (threads: 1): 1/1. Finished in 0ms.
Preparing original test run (threads: 1): 1/1. Finished in 248ms.
Running original tests (threads: 2): 2/2. Finished in 305ms.
Searching mutants across functions (threads: 4): 33/33. Finished in 12ms.
Applying filter: no debug info (threads: 4): 116/116. Finished in 1ms.
Applying filter: file path (threads: 4): 92/92. Finished in 11ms.
Applying filter: junk (threads: 4): 0/10In file included from ../sw/src/millisec_timer_unix.c:1:
/usr/include/time.h:29:10: fatal error: 'stddef.h' file not found
#include <stddef.h>
         ^~~~~~~~~~
Applying filter: junk (threads: 4): 10/10. Finished in 66ms.
No mutants found. Mutation score: infinitely high

Total execution time: 895ms
```

When I spoke to Alex Denisov he suggested that this might be a bug where Mull expects the commands to be fed as a single string. 

Seeing as Clang (which is the supported compiler for the project) outputs compilation databases in array-of-string format, it would be appreciated if array-of-string support was added to Mull.

**Comment by stanislaw** [comment]
I have solved this in mull-integration-tests by writing an additional script, see [example](https://github.com/mull-project/mull-integration-tests/blob/master/tests/mutations/and_or/01_no_mutations/sample.cpp#L4). 

The solution is not perfect but it allowed me to move forward.

**Comment by Warwolt** [comment]
Hi, thanks for the quick response. That link only seems to lead me to some kind of test runner entry point. Could you provide some detail of how the proposed workaround works, or a link to the script itself?

**Comment by stanislaw** [comment]
Sure! The first one is probably very similar to your sed action:

https://github.com/mull-project/mull-integration-tests/blob/master/tools/compilation_database.sh

The second one actually does the conversion:

https://github.com/mull-project/mull-integration-tests/blob/master/tools/compilation_database.py

**Comment by stanislaw** [comment]
It seems like this issue was not fixed by #632 because we also need to teach Mull how to recognize input without leading and trailing braces `[` and `]`. I have tried to implement a workaround here: https://github.com/mull-project/mull/compare/comp-db-fix?expand=1 (you no longer have to do any `sed` actions). But @AlexDenisov and I are not sure if we want to enable that workaround to work in the master branch because it makes it unclear how to distinguish between this `-MJ case` where we just need to add braces and other issues like a malformed JSON. This will probably be an ongoing discussion.

**Comment by stanislaw** [comment]
We are fixing the `file name issue` though: https://github.com/mull-project/mull/pull/633.

**Comment by Warwolt** [comment]
I'm not sure if Mull should necessarily be recognizing the input without the brackets, since I think proper compilation databases in general are expected to include them? I might be wrong, but it seems like a more straightforward solution and one that can be communicated to the users of Mull?
