### ISSUE TITLE
IDE reporter: improved

### ISSUE THREAD

**Issue by chgans** [mull-project/mull#659]
I use a python script that convert build logs to JUnit files (available here https://github.com/PSPDFKit-labs/clang-tidy-to-junit)
This scripts filters out only 'main errors' messages, for this it relies on the fact that modern compilers have a diagnostic flag hint in their message, eg `path/to/file.cpp:123:45: warning: unused function 'SomeFunction' [-Wunused-function]`, the hint here is `[-Wunused-function]`

It would be nice if the IDE reporter could output this, eg it could be the name of the mutation `[cxx_add_to_sub]`.

**Comment by stanislaw** [comment]
@AlexDenisov this looks like a very useful suggestion to me. I can confirm that Jenkins' Warnings NG plugin also recognizes such hints.

Could you think of using something else except mutator type as a hint? From my side, I guess that no and the strings like `cxx_add_to_sub` are a good fit for the hint.

What do you think?

**Comment by AlexDenisov** [comment]
It sounds like a good idea, folks. Who is willing to send the patch? 😄

**Comment by stanislaw** [comment]
I could do it very easy but @chgans you are also welcome :)

**Comment by stanislaw** [comment]
Just to make sure that it is what we need:

I have done this over the lunch break:

```
/sandbox/mull/tests-lit/tests/options/-ide-reporter-show-killed/03_one_surviving_one_killed/sample.cpp:42:19: warning: Survived: Replaced + with - [cxx_add_to_sub]
```

Does it look correct to you @AlexDenisov @chgans ?

**Comment by AlexDenisov** [comment]
I don't know whether it's correct or not, but this is exactly how I understood it :)

**Comment by stanislaw** [comment]
I think I can open a Pull Request this evening then already.

**Comment by stanislaw** [comment]
@chgans the #660 has already been merged to master. Would you mind building Mull from the master branch and checking that it does exactly what you need? Thanks.

**Comment by chgans** [comment]
I will test it next week. Might try as a patch on top of the latest release.
I'm trying to add mull to our CI pipeline (Jenkins), so sorry, i would prefer to stick with 'stable' release.
