### ISSUE TITLE
CppUTest integration pollutes project CMake configuration

### ISSUE THREAD

**Issue by gebart** [mull-project/mull#754]
CppUTest adds a number of generic settings to the CMake configuration which is confusing because they do not affect the mull build, only CppUTest library build. The docstrings for the settings are also very generic and do not mention CppUTest at all.

some examples:

```cmake
option(STD_C "Use the standard C library" ON)
option(STD_CPP "Use the standard C++ library" ON)
option(CPPUTEST_FLAGS "Use the CFLAGS/CXXFLAGS/LDFLAGS set by CppUTest" ON)
option(MEMORY_LEAK_DETECTION "Enable memory leak detection" ON)
option(EXTENSIONS "Use the CppUTest extension library" ON)
option(LONGLONG "Support long long" OFF)
option(MAP_FILE "Enable the creation of a map file" OFF)
option(COVERAGE "Enable running with coverage" OFF)
option(C++11 "Compile with C++11 support" OFF)
option(WERROR "Compile with warnings as errors" OFF)

option(TESTS "Compile and make tests for the code?" ON)
option(TESTS_DETAILED "Run each test separately instead of grouped?" OFF)
option(TESTS_BUILD_DISCOVER "Build time test discover" ON)

option(EXAMPLES "Compile and make exaples?" OFF)

option(VERBOSE_CONFIG "Print configuration to stdout during generation" ON)
```

This could be worked around by building CppUTest as an external project and adding it as an imported library instead of including it via `add_subdirectory()`

**Comment by gebart** [comment]
https://cmake.org/cmake/help/latest/module/ExternalProject.html is probably a better fit for this dependency.

**Comment by AlexDenisov** [comment]
I think it doesn't need to be added to the CMake build system. It's enough if it's just there as a submodule.
