### ISSUE TITLE
Segmentation fault after "parseBitcodeFile failed: can't skip to bit 1561952 from 320"

### ISSUE THREAD

**Issue by practicalswift** [mull-project/mull#768]
First:

Thanks for a really cool project @AlexDenisov and contributors! I love it! :)

Now to my issue:

When trying to use Mull for Bitcoin Core I ran in to the following issue:

```
$ mull-cxx --version
Mull: LLVM-based mutation testing
https://github.com/mull-project/mull
Version: 0.7.0
Commit: 1638698
Date: 28 Mar 2020
LLVM: 9.0.0
$ git clone https://github.com/bitcoin/bitcoin
$ cd bitcoin/
$ ./autogen.sh
$ CC='clang-9 -fembed-bitcode -g' CXX='clang++-9 -fembed-bitcode -g' ./configure --disable-wallet --disable-bench --disable-asm --disable-zmq --without-daemon --with-gui=no --without-miniupnpc
$ mull-cxx -test-framework=CustomTest src/test/test_bitcoin
[info] Extracting bitcode from executable (threads: 1)
       [################################] 1/1. Finished in 1439ms
[info] Loading bitcode files (threads: 12)
       [#######-------------------------] 57/257
parseBitcodeFile failed: can't skip to bit 1561952 from 320
Segmentation fault (core dumped)
```

What am I doing wrong? :)

**Comment by AlexDenisov** [comment]
Hey @practicalswift, thanks for bringing this up :)

Everything you're doing is right, something is odd on our side. Which OS are you on? I'd like to take a look at it.

**Comment by practicalswift** [comment]
@AlexDenisov The machine is running standard Ubuntu 18.04, and `{llvm,clang}-9` is `9-2~ubuntu18.04.2`:

```
$ clang++-9 --version
clang version 9.0.0-2~ubuntu18.04.2 (tags/RELEASE_900/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

Thanks for the super quick response! :)

**Comment by AlexDenisov** [comment]
I can reproduce the problem, but I don't have a proper solution at hand.
The other option I can suggest is to try the `clang-10` together with a nightly build, i.e.:

```
> tail -n 1
deb https://dl.bintray.com/mull-project/ubuntu-18 nightly main
> sudo apt-get install mull=0.7.0-pr769
```

and then
```
CC=clang-10 ...
```

I Just tried it inside of a virtual machine and it seems to be passing the segfault thing, but then in my case, it is killed because of OOM. I'll need to do another round by giving the machine more memory, but I cannot say when this round happens :)

I hope it helps.

**Comment by AlexDenisov** [comment]
Please, give it a try using new IR frontend: https://mull.readthedocs.io/en/0.15.0/tutorials/HelloWorld.html
