### ISSUE TITLE
Adaptive timeouts

### ISSUE THREAD

**Issue by gebart** [mull-project/mull#776]
It would be useful to have the tool record the wall time taken to run each case in the initial instrumented test run as a baseline and provide a user configurable margin for timeouts instead of only specifying the timeout in absolute milliseconds.

Concrete use case:
I have a test suite at work which takes about a minute to run sequentially, but the majority of that time is spent within only a handful of the individual test cases, most other cases are very quick. In this situation it would be more useful to say that if a mutated test takes for example twice as long as the unmutated test, then it should be considered a timeout (+ some margin for measurement error if the original test run is very quick).

**Comment by AlexDenisov** [comment]
If I get it right, then this feature partially implemented: we do record execution time for each original test run, the subsequent runs against mutants are then capped by the execution time of the original test multiplied by 10 :)
I.e., if test A took 1 second to run and test B took only 100ms, then all the mutants will have timeouts set to 10s for test A and 1000ms for test B.
The `--timeout` config only applied on the original test runs.

The corresponding code is here: https://github.com/mull-project/mull/blob/master/lib/Parallelization/Tasks/MutantExecutionTask.cpp#L50-L61

If that's not what you meant, then please elaborate :)

**Comment by AlexDenisov** [comment]
@gebart I'll close this one as I believe the timeouts we have are adaptive (to a certain extent).
Please, do not hesitate to re-open if you have another idea or have an improvement in mind.
