### ISSUE TITLE
mull-cxx crashed on use --reporters=Elements

### ISSUE THREAD

**Issue by ligurio** [mull-project/mull#783]
### Description

mull-cxx crashed on use `--reporters=Elements`:
```
mull-cxx: /__w/mull/mull/lib/AST/ASTMutationStorage.cpp:37: const mull::ASTMutation &mull::ASTMutationStorage::getMutation(const std::string &, mull::MutatorKind, int, int) const: Assertion `storage.count(sourceFile) > 0' failed.
Aborted (core dumped)
```

Everything is fine on execution without option `--reporters=Elements`.

### How to reproduce:

```
$ git clone https://github.com/tarantool/tarantool
$ cd tarantool
$ mkdir build && cd build
$ cmake \
  -DCMAKE_CXX_FLAGS="-fembed-bitcode -g -O0" \
  -DCMAKE_BUILD_TYPE=Debug \ 
  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
  -DCMAKE_C_COMPILER="/usr/bin/clang" \
  -DCMAKE_CXX_COMPILER="/usr/bin/clang++" ..
$ make -j
$ mull-cxx -test-framework=CustomTest --reporters=Elements ./test/unit/int96.test
$ 
```

```
sergeyb@pony:~/sources/MRG/tarantool/build$ mull-cxx --version
Mull: LLVM-based mutation testing
https://github.com/mull-project/mull
Version: 0.8.0
Commit: 84f2f4d
Date: 13 Oct 2020
LLVM: 10.0.0
```

Ubuntu Focal 20.04 x86_64

**Comment by stanislaw** [comment]
Mutation Testing Elements require AST information which Mull can obtain from a compilation database.

The issue that you are hitting is most likely related to the fact that you have to specify additional flags to show Mull where it should find the compilation database. 

Please check this piece of documentation and see how the `-compdb-path` is specified.

https://mull.readthedocs.io/en/latest/fmtlibTutorial.html#junk-mutations

Our documentation could be better. And we could add an error message to handle this case and explain to a user that without a compilation database the reporting to Elements will not work. We might get to fixing both issues on the Christmas holidays 🎄

**Comment by ligurio** [comment]
I can confirm that everything works successfully if run mull-cxx with following options:
```
mull-cxx -test-framework=CustomTest --reporters=Elements -compdb-path compile_commands.json -compilation-flags="-isystem /usr/local/include \
-isystem /usr/lib/llvm-10/lib/clang/10.0.0/include \
-isystem /usr/include/x86_64-linux-gnu \
-isystem /usr/include" ./test/unit/int96.test

<snipped>

[info] Compiling original code (threads: 1)
       [################################] 1/1. Finished in 122ms
[info] Running mutants (threads: 8)
       [################################] 23/23. Finished in 2045ms
[info] Mutation Testing Elements reporter: generating report to ./1607618112.json
[info] Total execution time: 2380ms
```
