### ISSUE TITLE
Add comparison in SimpleTestFinderTest 

### ISSUE THREAD

**Issue by Quolyk** [mull-project/mull#81]
#61
Find a way to compare unique pointer `addMutationOperator` with `MutationOperator *` in `SimpleTestFinderTest`:
 - `FindMutationPoints_AddMutationOperator`
 - `FindMutationPoints_NegateConditionMutationOperator`
 - `FindMutationPoints_RemoteVoidFunctionMutationOperator`

**Comment by AlexDenisov** [comment]
TODO has gone already.
