### ISSUE TITLE
No mutation for statement where both operands are constants

### ISSUE THREAD

**Issue by ligurio** [mull-project/mull#840]
### Description

source code:
```
void f1() {
    puts("abc");
    int a = 0;
    a = 2 + 2;
    a = a + 2;
    a = 2 + a;
}
```

mutants in Mull output:
```
[info] Survived mutants (4/4):
/home/sergeyb/sources/mull_testing/func1.c:6:11: warning: Survived: Replaced + with - [cxx_add_to_sub]
    a = b + c;
          ^
/home/sergeyb/sources/mull_testing/func1.c:7:11: warning: Survived: Replaced - with + [cxx_sub_to_add]
    b = a - c;
          ^
/home/sergeyb/sources/mull_testing/main.c:7:11: warning: Survived: Replaced + with - [cxx_add_to_sub]
    a = a + 2;
          ^
/home/sergeyb/sources/mull_testing/main.c:8:11: warning: Survived: Replaced + with - [cxx_add_to_sub]
    a = 2 + a;
          ^
[info] Mutation score: 0%
[info] Total execution time: 161ms
```

Mutation for line `a = 2 + 2;` is absent.

### How-to reproduce:

1. `git clone https://github.com/ligurio/mull-testing`
2. cd mull-testing
3. make mutate

### Version

sergeyb@pony:~/sources/mull_testing$ mull-cxx --version
Mull: LLVM-based mutation testing
https://github.com/mull-project/mull
Version: 0.10.0-trunk1
Commit: 296ee8e
Date: 10 Mar 2021
LLVM: 11.0.0

**Comment by AlexDenisov** [comment]
Hi @ligurio, thanks for the report.

There are no mutants in this case because Clang does constant folding and lowers `2 + 2` as `4`.
This is the corresponding IR code:

```
  store i32 0, i32* %a, align 4 ; Line int a = 0;
  store i32 4, i32* %a, align 4 ; Line a = 2 + 2;
```

Since it happens way before the code translates into the LLVM IR, there is not much we can do with this issue.

**Comment by ligurio** [comment]
Got it, thanks for explanation.
I think it's worth to describe it in documentation because it's not obvious. What do you think?

**Comment by AlexDenisov** [comment]
Yeah, makes sense! I'm also thinking about whether it makes sense to add a flag to clang (e.g. `-fno-constant-folding` or something like that),
