### ISSUE TITLE
Experimental support of Swift.

### ISSUE THREAD

**Issue by stanislaw** [mull-project/mull#86]
I have tried `lli` with pure Swift hello world code [quickly](https://github.com/mull-project/mull-jit-lab/tree/master/lab-jit-swift) and it seems to not be complaining about any Objective-C stuff. 

Apple's [XCTest](https://github.com/apple/swift-corelibs-xctest) project seems to be a promising candidate for a test adapter in the same way like we currently support `Google Test` as an example adapter for C++.

**Comment by stanislaw** [comment]
I have updated the description here. cc @AlexDenisov @JDevlieghere @Quolyk .

**Comment by AlexDenisov** [comment]
Shall we close this one?

**Comment by AlexDenisov** [comment]
Oops, I meant to leave a comment, but closed by accident.
Anyways, feel free to reopen if needed.
