### ISSUE TITLE
Mull skips macros

### ISSUE THREAD

**Issue by AndreiBogdanPislaru** [mull-project/mull#870]
Hello, it's me again :D, I noticed that mull doesn't analyze a couple of file whose code is under #define, is this normal or do I keep missing some flags?

**Comment by AlexDenisov** [comment]
Mull skips any potential mutations that are part of the macro invocations.
One of the reasons is that the debug information is kinda broken with macros, for the following code:

```
#define something(x) x
/// ...
something(a + b)
```

mull generates `cxx_add_to_sub` mutant for the `a + b`, but the debug information for this expression points to the beginning of the macro:

```
something(a + b)
^
```
during the junk detection we cannot say for sure if the mutation is valid or not, so we discard it to be on the safe side.

I remember we touched this topic briefly while discussing AST mutations, but I don't recall the conclusion.
Maybe @stanislaw can add something? :)

**Comment by RobertoBagnara** [comment]
Would it be possible/sensible to apply Mull to the preprocessed sources?

**Comment by stanislaw** [comment]
> Would it be possible/sensible to apply Mull to the preprocessed sources?

There are two answers to this question:

1) It is one of the limitations of the IR-level mutations that we couldn't find a workaround for: imprecision of the debug information for the preprocessed parts.  

(see Alex's answer above)

This was a state of the previous versions of LLVM and there is a small chance that this could improve. This is something that we could check.

2) On the AST level, it should be possible to implement this, but we simply haven't done it yet. It is a good idea to include the mutations in the preprocessed sources to the AST roadmap here: #867 (done just now).

**Comment by RobertoBagnara** [comment]
On 04/06/21 10:16, Stanislav Pankevich wrote:
>     Would it be possible/sensible to apply Mull to the preprocessed sources?
> 
> There are two answers to this question:
> 
>  1. It is one of the limitations of the IR-level mutations that we couldn't find a workaround for: imprecision of the debug information for the preprocessed parts.
> 
> (see Alex's answer above)
> 
> This was a state of the previous versions of LLVM and there is a small chance that this could improve. This is something that we could check.
> 
>  2. On the AST level, it should be possible to implement this, but we simply haven't done it yet. It is a good idea to include the mutations in the preprocessed sources to the AST roadmap here: #867 <https://github.com/mull-project/mull/issues/867> (done just now).

Sorry, my comment was not very clear.  What I meant was to pass the code
through "gcc -E -P" and use Mull over the result.  I think this would
solve the problem of the OP, which is to Mull code using the X Macros
technique.

**Comment by AlexDenisov** [comment]
Hi @RobertoBagnara, it's certainly possible to run mull against preprocessed source code. As long as you can build an executable that has bitcode embedded in it you are good to go.

Though, you may get many more mutants that you want. As part of the normal run mull discards all the mutants that are coming from the "system" headers. I'm afraid in the case of a preprocessed file mull won't be able to distinguish between a "system" function and the "user" functions.

**Comment by OlekRaymond** [comment]
I did some hack-ery to get around this.

1. Write usage code as normal in a single `.cpp` file and mutation test it (if it's low scoring before macros it will be low scoring after macros)
1. Make a note of the all headers required.
2. Remove all headers from the source file except those containing the macros you want to expand.
1. Run the compiler pre-processor on the source file and save the result.
1. Add the includes back to the source file.
1. Include the `.cpp` file into your exe as usual.

Again, very much a hack but does seem to work, I would recommend it if your codebase/lib is mostly macros (e.g. a testing framework [like mine](https://github.com/OlekRaymond/CppUnit2Gtest/tree/main)). [Working example done in CMake with `.in` files](https://github.com/OlekRaymond/CppUnit2Gtest/blob/b9352f78ef0f25537f58cf3814638b02374bbd52/tests/CMakeLists.txt#L42-L86)

Hope this helps if someone is in a similar situation, though I would recommend reducing macro usage first.
