### ISSUE TITLE
Warning Original test failed

### ISSUE THREAD

**Issue by AndreiBogdanPislaru** [mull-project/mull#871]
Hello :D. I have a gtest that normally run for 3-4 minutes but if I use mull on it, it gives me a warning: original test failed , status: Timedout

        [warning] Original test failed
        test: main
        status: Timedout
        stdout: 'Running main() from /usr/src/googletest/googletest/src/gtest_main.cc
        [==========] Running 10 tests from 1 test suite.
        [----------] Global test environment set-up.
        [----------] 10 tests from Sunlight
        [--------Bunch of test running well--------]
        [ RUN      ] Sunlight.Radiance_range
        [2021-06-04 20:42:00.936946] [0x00007f8be4b17740] [debug]   hourly log mark
        [2021-06-04 20:42:00.963020] [0x00007f8be4b17740] [debug]   hourly log mark
        [2021-06-04 20:42:00.972673] [0x00007f8be4b17740] [debug]   hourly log mark
        [-----more Logs-----]
        [2021-06-04 20:42:03.542865] [0x00007f8be4b17740] [debug]   hourly log mark
        [2021-06-04 20:42:03.552432] [0x00007f8be4b17740] [debug]   hourly log mark
        [2021-06-04 20:42:03.561999] [0x00007f8be4b17740] [debug]   hourly log mark
        [2021-06-04 20:42:03.571556] [0x0000'
        stderr: ''
        
               [################################] 1/1. Finished in 3009ms

As you can see in Log the test runs for 3 secs.
I also tried to increase timer to 90000ms using `--timeout=90000` and it runs for a bit longer, 8 secs circa

        [ RUN      ] Sunlight.Radiance_range
        [2021-06-04 21:30:55.478251] [0x00007f3869edf740] [debug]   hourly log mark
        [-----more Logs-----]
        [2021-06-04 21:31:03.877599] [0x00007f3869edf740] [debug]   hourly log mark
        [2021-06-04 21:31:03.887255] [0x00007f3869edf740] [debug]   hourly log mark
        [2021-06-04 21:31:03.896910] [0x00007f3869edf740] [debug]   hourly log mark
        [2021-06-04 21:31:03.906'
        stderr: ''
        
               [################################] 1/1. Finished in 90019ms

It doesn't seems affect the number of mutations detected, but is a warning that bothers me a bit. There is a way to solve it?
Thank you very much.

P.S. I also incresed the timeout up to 10 minutes, but I had not appreciable results.

**Comment by AlexDenisov** [comment]
> P.S. I also incresed the timeout up to 10 minutes, but I had not appreciable results.

It should've fixed the problem if the original code finished after 3-4 minutes. Can you share the log with the 10 minutes timeout (omitting the test output logs)?

**Comment by AndreiBogdanPislaru** [comment]
That's all the log mull prints far now, i had to run it again, It is running significantly slowest.

        [info] Extracting bitcode from executable (threads: 1)
               [################################] 1/1. Finished in 52ms
        [info] Loading bitcode files (threads: 1)
               [################################] 7/7. Finished in 191ms
        [info] Sanity check run (threads: 1)
        [warning] Original test failed
        test: main
        status: Timedout
        stdout: 'Running main() from /usr/src/googletest/googletest/src/gtest_main.cc
        [==========] Running 10 tests from 1 test suite.
        [----------] Global test environment set-up.
        [ RUN      ] Sunlight.Radiance_range
        [2021-06-04 22:32:02.985946] [0x00007f4a6193c740] [debug]   hourly log mark
        [---Logs---]
        [2021-06-04 22:32:11.366417] [0x00007f4a6193c740] [debug]   hourly log mark
        [2021-06-04 22:32:11.376'
        stderr: ''  
               [################################] 1/1. Finished in 600177ms
        [info] Gathering functions under test (threads: 1)
               [################################] 1/1. Finished in 0ms
        [info] Applying function filter: no debug info (threads: 1)
               [################################] 1219/1219. Finished in 1ms
        [info] Applying function filter: file path (threads: 1)
               [################################] 1023/1023. Finished in 1ms
        [info] Instruction selection (threads: 1)
               [################################] 50/50. Finished in 6ms
        [info] Searching mutants across functions (threads: 1)
               [################################] 50/50. Finished in 2ms
        [info] Applying filter: no debug info (threads: 1)
               [################################] 55/55. Finished in 0ms
        [info] Applying filter: file path (threads: 1)
               [################################] 55/55. Finished in 0ms
        [info] Applying filter: junk (threads: 1)
               [################################] 55/55. Finished in 2941ms
        [info] Deduplicate mutants (threads: 1)
               [################################] 1/1. Finished in 1ms
        [info] Prepare mutations (threads: 1)
               [################################] 1/1. Finished in 0ms
        [info] Cloning functions for mutation (threads: 1)
               [################################] 7/7. Finished in 106ms
        [info] Removing original functions (threads: 1)
               [################################] 7/7. Finished in 17ms
        [info] Redirect mutated functions (threads: 1)
               [################################] 7/7. Finished in 0ms
        [info] Applying mutations (threads: 1)
               [################################] 30/30. Finished in 0ms
        [info] Compiling original code (threads: 1)
               [################################] 7/7. Finished in 1203ms
        [info] Link mutated program (threads: 1)
        [info] Compiled executable: /tmp/mull-35eeca.exe
               [################################] 1/1. Finished in 1283ms
        [info] Warm up run (threads: 1)
        [################################] 1/1. Finished in 600083ms
        [info] Baseline run (threads: 1)
        [-----Still Running-----]

**Comment by AndreiBogdanPislaru** [comment]
I take it back, the warning affects definitively the mutations, while mull detect a certain ammount of mutations it seems it's not able to mutate theme and consider theme killed.
This is the script inside the make i use to start mull

    #!/bin/sh
    
    mull-cxx --linker=clang++-10 --linker-flags="-lpthread -lboost_log /usr/local/lib/libgtest_main.a /usr/local/lib/libgtest.a" \
    --include-path=$2  \
    -compilation-flags="\
    -isystem /usr/lib/llvm-10/lib/clang/10.0.0/include \
    -isystem @PATH_DIRECTORY_INCLUDE@ \
    -isystem @PATH_DIRECTORY_SYSTEM@ 
    -isystem @PATH_DIRECTORY_TEST@/Utilities " $1

$2 = the file I want to mutate
$1 = the executable

Anyway the problem occurs only when i call a function several time, something like 24*100*365*3600 times, could be bacause a some sort of mull buffer filled, or a sort of block to AST that avoids to many branches?

**Comment by AlexDenisov** [comment]
Yeah, if the original test finishes in 3-4 minutes, but Mull timeouts after 10 minutes, then it's certainly a bug on our side.

**Comment by stanislaw** [comment]
@AndreiBogdanPislaru here my 50 cents:

1) Which kind of code are you running? Is this a pure computation, i.e. algorithm, or you also have things like reading to files, accessing network, signals or timers?

2) 

> Anyway the problem occurs only when i call a function several times, something like 24 * 100 * 365 * 3600 times, could be because a some sort of mull buffer filled, or a sort of block to AST that avoids the creation of too many branches?

2a) Can you confirm that if you run your function only once, then everything works?

2b) Could you print "Running function round N" and let us know after how many rounds your function timeouts / fails?

The strategy for solving this would be to find a delta between the part that works and the part that no longer works. After that, it could be easier to identify the contributing cause.

**Comment by AndreiBogdanPislaru** [comment]
Hello @stanislaw :D.
1. The code just simulate passing time, every hour a log is printed (an hour correspond at 360.000 function calls).
2a. I use the same function also to test the code after one our passing and one day passing and mull does not complain.
2b. I introduce a counter to see how many times the inner function (which simulate one second passing) is called and mull stops the test after simulated 117 day, more precisely after 1.010.880.021 calls to the inner function, that with `--timeout=120000`, i tested also with `--timeout=60000`, but there is no difference.

**Comment by m42e** [comment]
probably the #915 will also fix this issue. The way timeout was passed to report seemed to not cause the expected behavior.

**Comment by m42e** [comment]
@AndreiBogdanPislaru Would you mind having a look if this is also fixed?

**Comment by AndreiBogdanPislaru** [comment]
Oh yes, I was waiting for the last release, the problem now is fixed, thank you!!
