### ISSUE TITLE
Bug? variable not initialized

### ISSUE THREAD

**Issue by AndreiBogdanPislaru** [mull-project/mull#875]
Hello again :D, I use a counter to kill the mutations inside a for loop, but I 've just noticed that if the counter has no value assigned mull gives me a 100% score and ignore all the mutations inside the code.

      uint32_t counter;
      for(uint32_t i = 0; i <= UINT8_MAX; i++){
        //some code
      
        counter++;
      }
      EXPECT_EQ(counter, UINT8_MAX + 1);

RESULT: All mutation have been killed, Mutation score: 100%

      uint32_t counter = 0;
      for(uint32_t i = 0; i <= UINT8_MAX; i++){
        //some code
      
        counter++;
      }
      EXPECT_EQ(counter, UINT8_MAX + 1);

RESULT: mull prints all mutations left.

In both cases all gtests pass.

**Comment by AndreiBogdanPislaru** [comment]
Hello @AlexDenisov, thank you for the response, I immagine that not-initialized values lead to an undefined behaviour, in this case it seems the compiler luckly sets the counter to zero by itself, what i meant is that if I have 70 killed mutations on 100, and I do not initialized the counter, mull gives me a 100% score instead of 70%. I'm just courios why, I mean, if all tests pass, it means that the Gtest executable reads the first value of counter as zero, shouldn't mull do the same?

**Comment by AlexDenisov** [comment]
That's the point of undefined behaviour.
Given this simple program:

```c
extern int printf(const char *, ...);

int main() {
  int x;
  printf("%d\n", x);
  return 0;
}
```

compiled with clang

```bash
$ clang main.c
```

You may get 10 different values for 10 separate runs.
This is what I get on macOS:

```bash
$ for in in `seq 1 10`; do ./a.out; done
324861989
443600933
239575077
221208613
473215013
349106213
338898981
213913637
415019045
318631973
```

And this is what I get on Linux:

```bash
$ for in in `seq 1 10`; do ./a.out; done
0
0
0
0
0
0
0
0
0
0
```

The result of execution of this program varies depending on a compiler, compiler version, optimization levels, OS, environment, etc.

---

With that being said, there can be a bug in Mull, but we just cannot reason about it if the behaviour of the program itself is not well defined 😄

**Comment by AndreiBogdanPislaru** [comment]
Nice, I understood, thank you very much :D
