### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by AndreiBogdanPislaru** [mull-project/mull#880]
Hello, it's me again :D, i checked the documentation and i can't find instructions to install mull on Windows, so I immagine mull doesn't support Windows, didn't it?

Thank you very much.

**Comment by stanislaw** [comment]
Hi again 😄 

Previously, Mull had no support for Windows but recently, Mull has been undergoing some architectural changes, some of which have been released already. Two particular changes that have been released a few months ago were the removal of LLVM JIT and change in how Mull executes the child processes (`reproc` cross-platform library is being used now). With these changes, the chances are that Mull should work on Windows.

The current state is that neither Alex nor me haven't tried setting up Mull on Windows. If you really need Mull to run on Windows, you could simply try doing it yourself with some pointers from our side.

The first challenge would be to build Mull's executable using CMake and make sure that everything compiles. The second is a runtime challenge - to make sure that Mull does the same thing as on macOS and Linux.

@AlexDenisov would you add something to this?

**Comment by AndreiBogdanPislaru** [comment]
@stanislaw Thank you very much for the response, I really apprecciate :D
