### ISSUE TITLE
Mull stops working properly after many logs printed

### ISSUE THREAD

**Issue by AndreiBogdanPislaru** [mull-project/mull#888]
Hello, I'm making unit tests for a program that prints a lot of logs and I noticed that at some point Mull cant handle the logs anymore. I tried with `no-test-output` flag but nothing changed.
I have reproduced the problem with this program:
 
      #include <limits.h>
      #include <cstdio>
      
      bool valid_age(int age) {
        if (age >= 21) {
          return true;
        }
        return false;
      }
      
      int main() {
        int test1 = valid_age(25) == true;
        if (!test1) {
          /// test failed
          return 1;
        }
      
        int test2 = valid_age(20) == false;
        if (!test2) {
          /// test failed
          return 1;
        }
      
        for (int i = 0; i < INT_MAX; ++i)
        {
          printf("COUNTER: %d\n", i);
        }
        /// success
        return 0;
      }

This is the output:

      andrei2@andrei2-VirtualBox:~/Scrivania$ mull-cxx hello_world
      [info] Extracting bitcode from executable (threads: 1)
             [################################] 1/1. Finished in 0ms
      [info] Loading bitcode files (threads: 1)
             [################################] 1/1. Finished in 1ms
      [info] Sanity check run (threads: 1)
      [warning] Original test failed
      test: main
      status: Timedout
      stdout: 'COUNTER: 0
      
      [...more counter prints and the rest of the stuff...]
      
      [info] Running mutants (threads: 1)
             [################################] 4/4. Finished in 30080ms
      [info] All mutations have been killed
      [info] Mutation score: 100%
      [info] Total execution time: 40333ms

**Comment by AlexDenisov** [comment]
The reproducer you have will take several minutes to compute. Are you sure in your original case the test finishes in a reasonable time?

**Comment by AlexDenisov** [comment]
Ok, I think I misunderstood you in the first place. I see the issue and I'll investigate it.

**Comment by AndreiBogdanPislaru** [comment]
Thank you for the rapid response :D, I really appreciate your effort. In my case the exacutable finishes immediately, but when I mull it, it takes few more seconds

**Comment by AndreiBogdanPislaru** [comment]
In the original case, the one that concern making tests for the program, mull worked well until I have added one last test, after some investigation I noticed that the problem was caused by a sort of limit that involves the number of characters printed.

**Comment by AlexDenisov** [comment]
Ok, I'm trying to reproduce this and seeing identical results to what you've posted.
Could you please explain exactly what do you expect and what happens instead? I've confused myself twice already 😅

**Comment by AndreiBogdanPislaru** [comment]
Ok, at the beggining I thought the problem was caused by the excessive number of log printed, but I did some tests with the value of timeout increased and mull gives me a different result, but still not the one I expect. This is the new reproducer:
        
        #include <limits.h>
        #include <cstdio>

        bool valid_age(int age) {
          if (age >= 21) {
            return true;
          }
          return false;
        }
        
        int main() {
          int test1 = valid_age(25) == true;
          int sum = 0;
          if (!test1) {
            /// test failed
            return 1;
          }
        
          int test2 = valid_age(20) == false;
          if (!test2) {
            /// test failed
            return 1;
          }
        
          for (int i = 0; i < INT_MAX; ++i)
          {
            //printf("%d\n", i);   ==> I made a change here because it was taking a lot of time to finish
            sum = 4*3;
          }
          /// success
          return 0;
        }

this it the command:
        
        clang -fembed-bitcode -g hello_world.cc -o hello_world
        mull-cxx --timeout=1000000 hello_world

and this is the given result:

        [info] Running mutants (threads: 1)
               [################################] 4/4. Finished in 2908ms
        [info] Survived mutants (1/4):
        /home/andrei2/Scrivania/hello_world.cc:5:11: warning: Survived: Replaced >= with > [cxx_ge_to_gt]
          if (age >= 21) {
                  ^
        [info] Mutation score: 75%
        [info] Total execution time: 12114ms

and this what I expect as the result(This result is given decreasing the number of for loops):

        [info] Running mutants (threads: 1)
               [################################] 7/7. Finished in 65ms
        [info] Survived mutants (3/7):
        /home/andrei2/Scrivania/hello_world.cc:5:11: warning: Survived: Replaced >= with > [cxx_ge_to_gt]
          if (age >= 21) {
                  ^
        /home/andrei2/Scrivania/hello_world.cc:25:21: warning: Survived: Replaced < with >= [cxx_lt_to_ge]
          for (int i = 0; i < 10; ++i)
                            ^
        /home/andrei2/Scrivania/hello_world.cc:25:21: warning: Survived: Replaced < with <= [cxx_lt_to_le]
          for (int i = 0; i < 10; ++i)
                            ^
        [info] Mutation score: 57%
        [info] Total execution time: 238ms

I also double the timeout value for mulling in the original project, but it gives me the same result, and I don't know why, the last test I added it's not very different from the previous one(there are a total of 46 tests) , they call the same function but under different conditions so the time taken to run should be very similar therefore doubling the timeout should be enough, but seems it has no effect.

**Comment by AndreiBogdanPislaru** [comment]
@AlexDenisov  Hello, I recorded also a video to better show the problems about the timeout, in the first part I show what happen increasing the `-timeout,` greater is the `-timeout` slower mull runs, in the last part I show how I "fixed" the problem.

https://streamable.com/n8sdgk

**Comment by m42e** [comment]
I have a similar issue. Tests take normally a reasonable amount of milliseconds. When running in mill with timeout 30000 the initial sanitize run without modification times out already. I am currently trying to get a closer look in what’s happening

**Comment by m42e** [comment]
@AndreiBogdanPislaru you could try with https://github.com/mull-project/mull/pull/915 worked for me

**Comment by AndreiBogdanPislaru** [comment]
@m42e Thank you very much. I confirm, now i don't have the timedout problem anymore after udpating to 0.13.0 V, but the problem with workers still persist(#887). Currently I'm using llvm version 12.0.0.
