### ISSUE TITLE
Trying to package mull, issue with LibEBC

### ISSUE THREAD

**Issue by mayl** [mull-project/mull#897]
I've been trying to package `mull` for `nixos` and hit a snag when building `LibEBC`.  In particular, it seems like upstream `LibEBC` uses the `pkg-config` mechanism in `cmake` to find `libxml` but [this commit](https://github.com/AlexDenisov/LibEBC/commit/3b1672e7d3d1358f99576445ac85eb41383cc1de) of your fork changed to hard code a path to it under `usr`, but this is not where `nixos` installs `libxml2`.  Your fork also seemed to remove the `LIBXML2_LIBRARY` and `LIBXML2_INCLUDE_DIR` variables which I could override from the command line to help `cmake` find `libxml2`.

Can you provide any additional context as to why this change was made?  I'm reluctant to propose a PR changing this back without understanding why it was done this way in the first place.  Would you be open to modifying `LibEBC` build to enable specifying a `libxml2` path when building?

**Comment by mayl** [comment]
Quick update, was able to confirm that I can build making the below change which I think more or less just reverts some previous changes (I'm not too well versed in `cmake`)

```
diff --git a/lib/CMakeLists.txt b/lib/CMakeLists.txt
index 4e3266b..bb32a8c 100644
--- a/lib/CMakeLists.txt
+++ b/lib/CMakeLists.txt
@@ -3,9 +3,10 @@ include(CheckLibraryExists)

 # LibXml2 Dependency
 find_package(PkgConfig)
-#pkg_check_modules(LIBXML2 libxml-2.0 IMPORTED_TARGET)
+find_package(LibXml2 REQUIRED)
+pkg_check_modules(LIBXML2 libxml-2.0 IMPORTED_TARGET)

-include_directories(${CMAKE_OSX_SYSROOT}/usr/include/libxml2)
+include_directories(${LIBXML2_INCLUDE_DIR})

 if (NOT TARGET LLVMCore)
   # LLVM Dependency
```

**Comment by AlexDenisov** [comment]
IIRC it was related to our attempt to support FreeBSD, I think that specific piece can be reverted and we should be good to go.

**Comment by AlexDenisov** [comment]
@mayl mull-cxx and LibEBC are gone now, so you can give it another try :)
