### ISSUE TITLE
Mull eats too many memory on mutants generation

### ISSUE THREAD

**Issue by ligurio** [mull-project/mull#899]
Generating of mutants for postgres (see #859) or cmake (see #862) with default options (like a number of workers) cannot finished due to killing by OOM. The mull-cxx eats about 15Gb of RAM.

Workaround: Reduce the number of workers to 2-3.

Feel free to close an issue if consumption of such enormous of memory is ok.

sergeyb@pony:~$ mull-cxx --version
Mull: LLVM-based mutation testing
https://github.com/mull-project/mull
Version: 0.11.0
Commit: ce7a538
Date: 13 Jun 2021
LLVM: 11.0.0

**Comment by AlexDenisov** [comment]
Could you give a try to the new IR frontend?
E.g.:
```
CC=clang CXX=clang++ \
  CXXFLAGS="-O1 -fpass-plugin=/usr/lib/mull-ir-frontend-9 -fexperimental-new-pass-manager -g -grecord-command-line" \
  CFLAGS="-O1 -fpass-plugin=/usr/lib/mull-ir-frontend-9 -fexperimental-new-pass-manager -g -grecord-command-line" \
  ./configure
```

Memory consumption should not be that big anymore.

**Comment by ligurio** [comment]
> Could you give a try to the new IR frontend?

Problem is gone with Mull 0.15.1. Thanks!
