### ISSUE TITLE
Installation documentation outdated?

### ISSUE THREAD

**Issue by gjtimmerman** [mull-project/mull#954]
If I follow the installation documentation I seem to have installed a deprecated version.

**Comment by AlexDenisov** [comment]
Could you tell a bit more? Which OS and which version are you trying to install?

**Comment by AlexDenisov** [comment]
Here is an example usage, if it helps https://github.com/mull-project/mull/blob/main/.github/workflows/mull-20.04.yml

**Comment by RainyTong** [comment]
Hi Alex,
I am using mac os 11.01 and trying to use brew to install Mull:
`brew install mull-project/mull/mull-stable`
However, I got this error message:
```
==> Downloading https://dl.bintray.com/mull-project/macos/Mull-0.9.0-LLVM-11.0-macOS-10.15.7.zip
Warning: Transient problem: HTTP error Will retry in 1 seconds. 3 retries     
Warning: left.
Warning: Transient problem: HTTP error Will retry in 2 seconds. 2 retries     
Warning: left.
Warning: Transient problem: HTTP error Will retry in 4 seconds. 1 retries     
Warning: left.
-=O#- #  #    #                                                               
curl: (22) The requested URL returned error: 502 Bad Gateway
Error: mull-stable: Failed to download resource "mull-stable"
Download failed: https://dl.bintray.com/mull-project/macos/Mull-0.9.0-LLVM-11.0-macOS-10.15.7.zip
```

Could you please help me?

**Comment by gjtimmerman** [comment]
I use Ubuntu 18.04 and I used the installation documentation to install mull:

curl -1sLf 'https://dl.cloudsmith.io/public/mull-project/mull-stable/setup.deb.sh' | sudo -E bash
sudo apt-get update
sudo apt-get install mull

It installed 'mull-cxx-9' and when I executed:
'mull-cxx-9 --version' it said that this version was deprecated.

**Comment by AlexDenisov** [comment]
@RainyTong unfortunately, homebrew packages are outdated. Currently, I can only suggest downloading the packages directly, for example from [here](https://cloudsmith.io/~mull-project/repos/mull-stable/packages/detail/raw/mull-13/0.15.0/).

---

@gjtimmerman the tool itself (`mull-cxx-X`) is deprecated, but the package comes with `mull-ir-frontend-9`.
Once you install `mull-9` (not `mull`), then you can check where the files are:
```
$ dpkg-query -L mull-9
/usr
/usr/bin
/usr/bin/mull-cxx-9
/usr/bin/mull-runner-9
/usr/lib
/usr/lib/mull-ir-frontend-9
```

**Comment by AlexDenisov** [comment]
@RainyTong I added a ticket for your issue https://github.com/mull-project/mull/issues/957

**Comment by RainyTong** [comment]
> @RainyTong I added a ticket for your issue #957

Thank you for your quick response and help! @AlexDenisov

**Comment by gjtimmerman** [comment]
@AlexDenisov : so if I understand it correctly: the tool I used to check whether the installation was correct that printed a deprecation message with a link to other releases, should not give me the idea that I installed an outdated version?
My suggestion is to let users check the installation in another way and not by using a deprecated tool.

**Comment by gjtimmerman** [comment]
@AlexDenisov : a further question about mull-9: as I understand it, that is the latest stable version, right? Should I also use clang-9 with it or can I use any version of clang with it?

**Comment by AlexDenisov** [comment]
> @AlexDenisov : so if I understand it correctly: the tool I used to check whether the installation was correct that printed a deprecation message with a link to other releases, should not give me the idea that I installed an outdated version?
> My suggestion is to let users check the installation in another way and not by using a deprecated tool.

You are right! I'll update the docs!

---

> @AlexDenisov : a further question about mull-9: as I understand it, that is the latest stable version, right? Should I also use clang-9 with it or can I use any version of clang with it?

This is a bit confusing, but the latest version of Mull is `0.15.0` (as of today). The `-9` (or any other number) indicates version of Clang/LLVM this version is built for.
So you should be using `clang-9` with `mull-9`, `clang-10` with `mull-10`, etc.

Now I see that the installation doc is broken, I can suggest looking at the tutorial instead https://mull.readthedocs.io/en/0.15.0/tutorials/HelloWorld.html
It was certainly updated.

**Comment by AlexDenisov** [comment]
@gjtimmerman the installation doc was indeed outdated. The fixed version is live: https://mull.readthedocs.io/en/latest/Installation.html
