### ISSUE TITLE
Where is mull-ir-frontend?

### ISSUE THREAD

**Issue by gjtimmerman** [mull-project/mull#955]
If I download packages from cloudsmith, they do not contain mull-ir-frontend-xx files. Where can I find them?

**Comment by AlexDenisov** [comment]
On Ubuntu, you should have it under `/usr/lib/mull-ir-frontend-xx`.
Which version of Mull and which `xx` are you installing?

**Comment by gjtimmerman** [comment]
I installed mull using the installation documentation and it installed mull-cxx-9 for me. When I saw this version was deprecated, I look at cloudsmith and I found a version for mull-10, but the package did contain mull-cxx-10, but no file for mull-ir-frontend-10. How can I install a newer version than version 9 or where can I find mull-ir-frontend for other versions?

**Comment by AlexDenisov** [comment]
Please, refer to the second part of this comment to find the IR frontend binary https://github.com/mull-project/mull/issues/954#issuecomment-1022616349
