### ISSUE TITLE
Mull cannot parse my cpp files

### ISSUE THREAD

**Issue by gjtimmerman** [mull-project/mull#959]
If I use mull-9 together with clang-9, I get the following error message (without the mull-flags it compiles without errors):

[warning] Mull cannot find config (mull.yml). Using some defaults.
[warning] Cannot parse file: '/home/instructor/ModularCalculation/CPP/ModularCalculation/ModularCalculation.cpp':
mull-cxx -Z-reserved-lib-stdc++ -O1 -fexperimental-new-pass-manager -fpass-plugin=/usr/lib/mull-ir-frontend-9 -g -grecord-command-line CPP/ModularCalculation/ModularCalculation.cpp CPP/ModularCalculationMain/ModularCalculationMain.cpp -o CalculationProg
Make sure that the flags provided to Mull are the same flags that are used for normal compilation.
[warning] Mull cannot find config (mull.yml). Using some defaults.
[warning] Cannot parse file: '/home/instructor/ModularCalculation/CPP/ModularCalculationMain/ModularCalculationMain.cpp':
mull-cxx -Z-reserved-lib-stdc++ -O1 -fexperimental-new-pass-manager -fpass-plugin=/usr/lib/mull-ir-frontend-9 -g -grecord-command-line CPP/ModularCalculation/ModularCalculation.cpp CPP/ModularCalculationMain/ModularCalculationMain.cpp -o CalculationProg
Make sure that the flags provided to Mull are the same flags that are used for normal compilation.

**Comment by AlexDenisov** [comment]
Is it the full output? The should be some other error messages. I'd expect something like `cannot find <stdarg.h>` or similar error.

There are two ways to handle this warning:
 - you can ignore it 😄 
 - you can add extra config to the `mull.yml`. Namely, you'd need to configure `compilerFlags` as described in this [doc](https://mull.readthedocs.io/en/0.15.0/tutorials/CompilationDatabaseAndJunk.html#junk-mutations)

---

We are in the process of transitioning from `mull-cxx` to `mull-ir-frontend`, so many pieces of the documentation are still covering the "old" approach.
If you hit any other snags - please feel free to open another issue or ping me on [discord](https://discord.gg/Hphp7dW).

**Comment by gjtimmerman** [comment]
I get an error from the compiler that says: "error: unsupported option '-Z-reserved-lib-stdc++'". But I don't pass that option. I only pass the '-lstdc++' as a linker option. Is that a problem?

**Comment by gjtimmerman** [comment]
Ignoring it is not a solution, because the generated output does not contain any mutants. I have to solve this issue to be able to use mull.

**Comment by gjtimmerman** [comment]
The `compilerFlags` are used to add include files. That doesn't seem to be the problem.

**Comment by AlexDenisov** [comment]
@gjtimmerman the `compilerFlags` can be used for everything, but I thought that's the `stdarg.h` issue.
Can you try reducing the issue to a small reproducer? Otherwise, it's pretty hard for the to debug without seeing what's happening.
Also, if you can share some more output/command you are running, that would help as well.

**Comment by gjtimmerman** [comment]
[MinimalCPPProgram.zip](https://github.com/mull-project/mull/files/7957891/MinimalCPPProgram.zip)

I attached a zip-file with a minimal program that gives the same errors. I included a shell-script that calls clang-9 so you can see which parameters I pass.

**Comment by AlexDenisov** [comment]
@gjtimmerman thank you so much! I can see the problem now.

I'll work on the fix, but as a workaround I can suggest either of the following:
1. Build each file separately and then link them together (the same way as any build system does).
2. Build the files together, but omit the `-grecord-command-line` and, optionally, provide a compilation database (`compile_commands.json`).

**Comment by gjtimmerman** [comment]
@AlexDenisov : Thanks, separate compilation steps solves my problem. The reason that I didn't do so initially, is that I followed the Tutorial. May be it is a good idea to mention this in the tutorial.

**Comment by AlexDenisov** [comment]
@gjtimmerman I added a note to the docs, thank you for reporting this issue!
