### ISSUE TITLE
Compile mutants with Makefile

### ISSUE THREAD

**Issue by RainyTong** [mull-project/mull#968]
Hi there,

My target program needs to be compiled with `Makefile` since there are a lot of dependency files. 
By running `mull-cxx`, is there a way to compile each generated mutant with a given `Makefile`?

Thank you!

**Comment by AlexDenisov** [comment]
@RainyTong not sure if I understood the question correctly.

Could you elaborate and tell what are you trying to achieve and what blocks you from doing that? :)

**Comment by RainyTong** [comment]
@AlexDenisov Thanks for your help. I am sorry that I misunderstood the logic behind `mull-cxx`. I thought each generated mutant needs to be recompiled to be able to run, but actually I just need to compile the original program once before using `mull-cxx`. The problem has been solved now. Sorry for that!
