### ISSUE TITLE
[error] Uh oh! Mull corrupted LLVM module.

### ISSUE THREAD

**Issue by RobertoBagnara** [mull-project/mull#993]
We just upgraded Mull from a very old version.
We are now using https://github.com/mull-project/mull/releases/download/0.17.1/Mull-12-0.17.1-LLVM-12.0-ubuntu-20.04.deb
Following the tutorials, I think we managed to revise all our scripting in the correct way, but now we stumble upon a bungh of errors of the form

<pre>
[error] Uh oh! Mull corrupted LLVM module.
Please, report the following error message here https://github.com/mull-project/mull/issues
Underlying error message:
Invalid indices for GEP pointer type!
  %7 = getelementptr inbounds %struct.m_uint8_t, %struct.m_uint8_t* %6, i32 0, i32 42, !dbg !226
...
</pre>

The attached typescript contains several occurrences:

[LOG.txt](https://github.com/mull-project/mull/files/8402132/LOG.txt)

**Comment by RobertoBagnara** [comment]
Sure, it is very short:

<code>
mutators:
 - all

timeout: 10000

quiet: false
</code>

**Comment by AlexDenisov** [comment]
I'd suggest sticking to `cxx_all` as `all` includes experimental mutators some of which are currently broken.
@RobertoBagnara could you give it a try?

**Comment by RobertoBagnara** [comment]
It seems to work now: thanks!

**Comment by AlexDenisov** [comment]
The `all` is not supposed to be used by end users, I'll add a warning when it happens to avoid confusion.
Thank you so much for bringing this up @RobertoBagnara!

**Comment by AlexDenisov** [comment]
I extended diagnostics to handle such cases here #1000.
